#pragma once
#define SCREEN_W 800
#define SCREEN_H 800
#define SCREEN_FPS 60
#define SCREEN_TICKS_PER_FRAME  1000/SCREEN_FPS


#define PUYO_MOV_DELAY 120
#define PUYO_FALL_DOWN 32 
#define PUYO_MOV_PHANT 400
//COLOR LIMITS
#define LIMITCOLORBELOW 1
#define LIMITCOLORBEYOND 5

//MATRIZ DEFINITION
#define MATRIZ_GAME_H 12
#define MATRIZ_GAME_W 12

//INITIAL VALUE OF PUYOS WITHIN MATRIZ
#define INI_SPACE_MATRIZ_Y 0
#define INI_SPACE_MATRIZ_X 2

//DIMENCION OF PLAY AREA
#define STAGE_W 256 //FROM MULTIPLY 32*6 + 32*3
#define STAGE_H 384 //FROM MULTIPLY 32*12

//INITIAL VALUE OF PUYO
#define INIT_PUYO_GRAPH_Y PLAY_TOP //INITIAL FROM TOP SPACE
#define INIT_PUYO_GRAPH_X INIT_BACKGOUNG_POS_X + PUYO_SIZE*3 //INITIAL IN THE 3 SPACE WITHIN PLAY AREA

//BACKGROUNG POSITION ON THE WINDOWS
#define INIT_BACKGOUNG_POS_X 30
#define INIT_BACKGOUNG_POS_Y 0
#define PUYO_SIZE 32 //PUYO SIZE


#define PLAY_LEFT INIT_BACKGOUNG_POS_X + PUYO_SIZE //DETERMINATE PLAY AREA LEFT
#define PLAY_TOP INIT_BACKGOUNG_POS_Y + PUYO_SIZE //DETERMINATE PLAY AREA RIGHT

#define NUM_PUYO_TEXTURES 0 //PUYO SIZE OF TEXTURES

enum state 
{
	MAIN_MENU = 0,
	GAMEPLAY,
	OVER,
	SCORE,
	CREDITS,
	IN_GAME_SUB_MENU
};
enum User{
	UserPhanton = 0,
	User
};
enum Win {
	winUser = 0,
	WinPhant,
	Same
};
enum Puyo_color {
	PUYO_RED = 1,
	PUYO_GREEN,
	PUYO_YELLOW,
	PUYO_BLUE,
	PUYO_BLACK,
	PUYO_PHANT
};
